- hosts: hosts 
  tasks:
    - name: configure sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: "^(#)?{{item.key}}"
        line: "{{item.key}} {{item.value}}"
        state: present
      loop:
        - {key: "PermitRootLogin", value: "no"}
        - {key: "PasswordAuthentication", value: "no" }
        - {key: "Port", value: "22"}
        - {key: "MaxAuthTries", value: "2"}
        - {key: "MaxSessions", value: "2"}
        - {key: "PubkeyAuthentication", value: "yes"}
        - {key: "AllowUsers", value: "admin"}
      become: yes

    - name: Reload Systemd SSH Service
      ansible.builtin.systemd:
        name: sshd
        state: reloaded
      become: yes
