- hosts: onboarding
  become: true
  tasks:
    - name: update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest

    - name: Install sudo
      apt:
        name:
          - sudo
        state: present
        update_cache: yes
